# BurnInWatch — Dataset Discovery & Initial EDA

This notebook performs **dataset discovery only**. It does not invent labels, alter measurements, or train a model yet.

Goals:
- inventory every file in the NASA IGBT dataset
- inspect `.mat` variables and dimensions
- inspect Excel workbooks and sheets
- identify likely time-series / device-level data
- export inventory CSVs for the next analysis stage

Run this first and share the important outputs before we decide preprocessing, feature engineering, train/test splitting, or the anomaly-detection model.

In [1]:
from pathlib import Path
import os
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", 100)
pd.set_option("display.max_rows", 200)

print("Environment ready")

Environment ready

In [3]:
# Change this only if your folder is somewhere else.
# Expected structure:
# BurnInWatch/
#   dataset/
#      Data/
#         ...

DATA_ROOT = Path("dataset/Data").resolve()

print("Dataset root:", DATA_ROOT)
print("Exists:", DATA_ROOT.exists())

if not DATA_ROOT.exists():
    print("\nERROR: Change DATA_ROOT to your actual Data folder.")

Dataset root: C:\Users\Abhishek Kuma\Desktop\BurnInWatch\dataset\Data
Exists: True

In [4]:
# ============================================================
# COMPLETE FILE INVENTORY
# ============================================================

rows = []

if DATA_ROOT.exists():
    for path in sorted(DATA_ROOT.rglob("*")):
        if path.is_file():
            rows.append({
                "relative_path": str(path.relative_to(DATA_ROOT)),
                "filename": path.name,
                "extension": path.suffix.lower(),
                "size_kb": round(path.stat().st_size / 1024, 2),
                "size_mb": round(path.stat().st_size / (1024**2), 4)
            })

file_inventory = pd.DataFrame(rows)

print("Total files:", len(file_inventory))
display(file_inventory)

if not file_inventory.empty:
    print("\nFiles by extension:")
    display(
        file_inventory.groupby("extension")
        .agg(files=("filename", "count"), total_mb=("size_mb", "sum"))
        .sort_values("files", ascending=False)
    )

    file_inventory.to_csv("dataset_file_inventory.csv", index=False)
    print("\nSaved: dataset_file_inventory.csv")

Total files: 177

,relative_path,filename,extension,size_kb,size_mb
0,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,11.txt,.txt,0.06,0.0001
1,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Breakdown.csv,.csv,4.88,0.0048
2,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,LeakageIV.csv,.csv,4.88,0.0048
3,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Turn On.csv,.csv,4.88,0.0048
4,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,12.txt,.txt,0.06,0.0001
5,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Breakdown.csv,.csv,4.88,0.0048
6,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,LeakageIV.csv,.csv,4.88,0.0048
7,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Turn On.csv,.csv,4.88,0.0048
8,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,13.txt,.txt,0.06,0.0001
9,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Breakdown.csv,.csv,4.88,0.0048
10,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,LeakageIV.csv,.csv,4.88,0.0048
11,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Turn On.csv,.csv,4.88,0.0048
12,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,14.txt,.txt,0.06,0.0001
13,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Breakdown.csv,.csv,4.88,0.0048
14,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,LeakageIV.csv,.csv,4.88,0.0048
15,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Turn On.csv,.csv,4.88,0.0048
16,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,15.txt,.txt,0.06,0.0001
17,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Breakdown.csv,.csv,4.88,0.0048
18,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,LeakageIV.csv,.csv,4.88,0.0048
19,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Turn On.csv,.csv,4.88,0.0048
20,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,16.txt,.txt,0.06,0.0001
21,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Breakdown.csv,.csv,4.88,0.0048
22,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,LeakageIV.csv,.csv,4.88,0.0048
23,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Turn On.csv,.csv,4.88,0.0048
24,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,17.txt,.txt,0.06,0.0001
25,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Breakdown.csv,.csv,4.88,0.0048
26,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,LeakageIV.csv,.csv,4.88,0.0048
27,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Turn On.csv,.csv,4.88,0.0048
28,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,18.txt,.txt,0.06,0.0001
29,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Breakdown.csv,.csv,4.88,0.0048
30,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,LeakageIV.csv,.csv,4.88,0.0048
31,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Turn On.csv,.csv,4.88,0.0048
32,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,19.txt,.txt,0.06,0.0001
33,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Breakdown.csv,.csv,4.88,0.0048
34,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,LeakageIV.csv,.csv,4.88,0.0048
35,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Turn On.csv,.csv,4.88,0.0048
36,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,1A.txt,.txt,0.06,0.0001
37,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Breakdown.csv,.csv,4.88,0.0048
38,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,LeakageIV.csv,.csv,4.88,0.0048
39,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Turn On.csv,.csv,4.88,0.0048
40,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,1B.txt,.txt,0.06,0.0001
41,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Breakdown.csv,.csv,4.88,0.0048
42,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,LeakageIV.csv,.csv,4.88,0.0048
43,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Turn On.csv,.csv,4.88,0.0048
44,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,1C.txt,.txt,0.06,0.0001
45,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Breakdown.csv,.csv,4.88,0.0048
46,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,LeakageIV.csv,.csv,4.88,0.0048
47,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Turn On.csv,.csv,4.88,0.0048
48,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,1D.txt,.txt,0.06,0.0001
49,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Breakdown.csv,.csv,4.88,0.0048
50,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,LeakageIV.csv,.csv,4.88,0.0048
51,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Turn On.csv,.csv,4.88,0.0048
52,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,1E.txt,.txt,0.06,0.0001
53,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Breakdown.csv,.csv,4.88,0.0048
54,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,LeakageIV.csv,.csv,4.88,0.0048
55,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Turn On.csv,.csv,4.88,0.0048
56,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,1J.txt,.txt,0.06,0.0001
57,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Breakdown.csv,.csv,4.88,0.0048
58,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,LeakageIV.csv,.csv,4.88,0.0048
59,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Turn On.csv,.csv,4.88,0.0048
60,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,1K.txt,.txt,0.06,0.0001
61,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Breakdown.csv,.csv,4.88,0.0048
62,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,LeakageIV.csv,.csv,4.88,0.0048
63,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Turn On.csv,.csv,4.88,0.0048
64,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,1L.txt,.txt,0.06,0.0001
65,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Breakdown.csv,.csv,4.88,0.0048
66,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,LeakageIV.csv,.csv,4.88,0.0048
67,SMU Data for new devices\IGBT-IRG4BC30K\Part 1...,Turn On.csv,.csv,4.88,0.0048
68,SMU Data for new devices\IGBT-IRG4BC30K\Part 8...,8J.txt,.txt,0.06,0.0001
69,SMU Data for new devices\IGBT-IRG4BC30K\Part 8...,Breakdown.csv,.csv,4.88,0.0048
70,SMU Data for new devices\IGBT-IRG4BC30K\Part 8...,LeakageIV.csv,.csv,4.88,0.0048
71,SMU Data for new devices\IGBT-IRG4BC30K\Part 8...,Turn On.csv,.csv,4.88,0.0048
72,SMU Data for new devices\IGBT-IRG4BC30K\Part 8...,8K.txt,.txt,0.06,0.0001
73,SMU Data for new devices\IGBT-IRG4BC30K\Part 8...,Breakdown.csv,.csv,4.88,0.0048
74,SMU Data for new devices\IGBT-IRG4BC30K\Part 8...,LeakageIV.csv,.csv,4.88,0.0048
75,SMU Data for new devices\IGBT-IRG4BC30K\Part 8...,Turn On.csv,.csv,4.88,0.0048
76,SMU Data for new devices\IGBT-IRG4BC30K\Part 8...,8L.txt,.txt,0.06,0.0001
77,SMU Data for new devices\IGBT-IRG4BC30K\Part 8...,Breakdown.csv,.csv,4.88,0.0048
78,SMU Data for new devices\IGBT-IRG4BC30K\Part 8...,LeakageIV.csv,.csv,4.88,0.0048
79,SMU Data for new devices\IGBT-IRG4BC30K\Part 8...,Turn On.csv,.csv,4.88,0.0048
80,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,1.txt,.txt,0.06,0.0001
81,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Breakdown.csv,.csv,4.89,0.0048
82,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,LeakageIV.csv,.csv,4.97,0.0049
83,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Turn On.csv,.csv,4.89,0.0048
84,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,10.txt,.txt,0.06,0.0001
85,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Breakdown.csv,.csv,4.88,0.0048
86,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,LeakageIV.csv,.csv,5.00,0.0049
87,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Turn On.csv,.csv,4.89,0.0048
88,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,11.txt,.txt,0.06,0.0001
89,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Breakdown.csv,.csv,4.88,0.0048
90,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,LeakageIV.csv,.csv,5.01,0.0049
91,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Turn On.csv,.csv,4.89,0.0048
92,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,12.txt,.txt,0.06,0.0001
93,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Breakdown.csv,.csv,4.88,0.0048
94,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,LeakageIV.csv,.csv,5.01,0.0049
95,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Turn On.csv,.csv,4.88,0.0048
96,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,13.txt,.txt,0.06,0.0001
97,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Breakdown.csv,.csv,4.88,0.0048
98,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,LeakageIV.csv,.csv,5.00,0.0049
99,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Turn On.csv,.csv,4.89,0.0048
100,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,14.txt,.txt,0.06,0.0001
101,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Breakdown.csv,.csv,4.88,0.0048
102,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,LeakageIV.csv,.csv,5.01,0.0049
103,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Turn On.csv,.csv,4.89,0.0048
104,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,15.txt,.txt,0.06,0.0001
105,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Breakdown.csv,.csv,4.88,0.0048
106,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,LeakageIV.csv,.csv,4.99,0.0049
107,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Turn On.csv,.csv,4.89,0.0048
108,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,16.txt,.txt,0.06,0.0001
109,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Breakdown.csv,.csv,4.89,0.0048
110,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,LeakageIV.csv,.csv,5.01,0.0049
111,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Turn On.csv,.csv,4.88,0.0048
112,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,17.txt,.txt,0.06,0.0001
113,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Breakdown.csv,.csv,4.90,0.0048
114,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,LeakageIV.csv,.csv,5.00,0.0049
115,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Turn On.csv,.csv,4.89,0.0048
116,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,18.txt,.txt,0.06,0.0001
117,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Breakdown.csv,.csv,4.88,0.0048
118,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,LeakageIV.csv,.csv,5.01,0.0049
119,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Turn On.csv,.csv,4.89,0.0048
120,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,19.txt,.txt,0.06,0.0001
121,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Breakdown.csv,.csv,4.88,0.0048
122,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,LeakageIV.csv,.csv,5.02,0.0049
123,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Turn On.csv,.csv,4.89,0.0048
124,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,2.txt,.txt,0.06,0.0001
125,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Breakdown.csv,.csv,4.89,0.0048
126,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,LeakageIV.csv,.csv,4.98,0.0049
127,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Turn On.csv,.csv,4.89,0.0048
128,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,20.txt,.txt,0.06,0.0001
129,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Breakdown.csv,.csv,4.88,0.0048
130,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,LeakageIV.csv,.csv,5.02,0.0049
131,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Turn On.csv,.csv,4.89,0.0048
132,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,3.txt,.txt,0.06,0.0001
133,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Breakdown.csv,.csv,4.88,0.0048
134,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,LeakageIV.csv,.csv,4.99,0.0049
135,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Turn On.csv,.csv,4.89,0.0048
136,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,4.txt,.txt,0.06,0.0001
137,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Breakdown.csv,.csv,4.88,0.0048
138,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,LeakageIV.csv,.csv,5.02,0.0049
139,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Turn On.csv,.csv,4.89,0.0048
140,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,5.txt,.txt,0.06,0.0001
141,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Breakdown.csv,.csv,4.88,0.0048
142,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,LeakageIV.csv,.csv,5.01,0.0049
143,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Turn On.csv,.csv,4.89,0.0048
144,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,6.txt,.txt,0.06,0.0001
145,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Breakdown.csv,.csv,4.88,0.0048
146,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,LeakageIV.csv,.csv,5.02,0.0049
147,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Turn On.csv,.csv,4.89,0.0048
148,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,7.txt,.txt,0.06,0.0001
149,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Breakdown.csv,.csv,4.88,0.0048
150,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,LeakageIV.csv,.csv,5.02,0.0049
151,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Turn On.csv,.csv,4.89,0.0048
152,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,8.txt,.txt,0.06,0.0001
153,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Breakdown.csv,.csv,4.88,0.0048
154,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,LeakageIV.csv,.csv,5.02,0.0049
155,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Turn On.csv,.csv,4.89,0.0048
156,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,9.txt,.txt,0.06,0.0001
157,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Breakdown.csv,.csv,4.88,0.0048
158,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,LeakageIV.csv,.csv,5.02,0.0049
159,SMU Data for new devices\MOSFET-IRF520Npbf\Par...,Turn On.csv,.csv,4.89,0.0048
160,SMU Data for new devices\Readme.doc,Readme.doc,.doc,27.50,0.0269
161,Thermal Overstress Aging with DC at gate\20080...,20080429T135531.mat,.mat,10871.21,10.6164
162,Thermal Overstress Aging with DC at gate\Readm...,Readme.doc,.doc,50.00,0.0488
163,Thermal Overstress Aging with Square Signal at...,april22nd-23rdIgbtIRCG40BC30kd-A17.mat,.mat,85638.40,83.6312
164,Thermal Overstress Aging with Square Signal at...,Readme.doc,.doc,28.50,0.0278
165,Thermal Overstress Aging with Square Signal at...,Device2 1.mat,.mat,23801.04,23.2432
166,Thermal Overstress Aging with Square Signal at...,Device2b 1.mat,.mat,14152.06,13.8204
167,Thermal Overstress Aging with Square Signal at...,Device2check 1.mat,.mat,1065.40,1.0404
168,Thermal Overstress Aging with Square Signal at...,Device3 1.mat,.mat,21578.90,21.0731
169,Thermal Overstress Aging with Square Signal at...,Device3b 1.mat,.mat,12055.84,11.7733
170,Thermal Overstress Aging with Square Signal at...,Device3check 1.mat,.mat,757.95,0.7402
171,Thermal Overstress Aging with Square Signal at...,Device4 1.mat,.mat,24003.66,23.4411
172,Thermal Overstress Aging with Square Signal at...,Device4b 1.mat,.mat,31594.01,30.8535
173,Thermal Overstress Aging with Square Signal at...,Device5 1.mat,.mat,22895.83,22.3592
174,Thermal Overstress Aging with Square Signal at...,Device5check 1.mat,.mat,686.80,0.6707
175,Thermal Overstress Aging with Square Signal at...,Device Aging log.xls,.xls,24.50,0.0239
176,Thermal Overstress Aging with Square Signal at...,Readme.doc,.doc,29.00,0.0283

Files by extension:

           files  total_mb
extension
.csv         120    0.5780
.txt          40    0.0040
.mat          12  243.2627
.doc           4    0.1318
.xls           1    0.0239

Saved: dataset_file_inventory.csv

In [5]:
# ============================================================
# DIRECTORY TREE
# ============================================================

def print_tree(root, max_depth=5):
    root = Path(root)
    print(root.name + "/")

    for current, dirs, files in os.walk(root):
        current_path = Path(current)
        depth = len(current_path.relative_to(root).parts)

        if depth > max_depth:
            dirs[:] = []
            continue

        indent = "    " * depth

        for d in sorted(dirs):
            print(f"{indent}{d}/")

        for f in sorted(files):
            print(f"{indent}{f}")

if DATA_ROOT.exists():
    print_tree(DATA_ROOT)

Data/
SMU Data for new devices/
Thermal Overstress Aging with DC at gate/
Thermal Overstress Aging with Square Signal at gate/
Thermal Overstress Aging with Square Signal at gate and SMU data/
    IGBT-IRG4BC30K/
    MOSFET-IRF520Npbf/
    Readme.doc
        Part 11/
        Part 12/
        Part 13/
        Part 14/
        Part 15/
        Part 16/
        Part 17/
        Part 18/
        Part 19/
        Part 1A/
        Part 1B/
        Part 1C/
        Part 1D/
        Part 1E/
        Part 1J/
        Part 1K/
        Part 1L/
        Part 8J/
        Part 8K/
        Part 8L/
            11.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            12.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            13.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            14.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            15.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            16.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            17.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            18.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            19.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            1A.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            1B.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            1C.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            1D.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            1E.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            1J.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            1K.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            1L.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            8J.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            8K.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            8L.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
        Part 1/
        Part 10/
        Part 11/
        Part 12/
        Part 13/
        Part 14/
        Part 15/
        Part 16/
        Part 17/
        Part 18/
        Part 19/
        Part 2/
        Part 20/
        Part 3/
        Part 4/
        Part 5/
        Part 6/
        Part 7/
        Part 8/
        Part 9/
            1.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            10.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            11.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            12.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            13.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            14.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            15.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            16.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            17.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            18.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            19.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            2.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            20.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            3.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            4.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            5.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            6.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            7.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            8.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
            9.txt
            Breakdown.csv
            LeakageIV.csv
            Turn On.csv
    20080429T135531.mat
    Readme.doc
    Readme.doc
    april22nd-23rdIgbtIRCG40BC30kd-A17.mat
    Aging Data/
    SMU Parameter Characterization/
    Device Aging log.xls
    Readme.doc
        Device 2/
        Device 3/
        Device 4/
        Device 5/
            Device2  1.mat
            Device2b  1.mat
            Device2check  1.mat
            Device3  1.mat
            Device3b  1.mat
            Device3check  1.mat
            Device4  1.mat
            Device4b  1.mat
            Device5  1.mat
            Device5check  1.mat

## MATLAB inspection

The first critical question is: **what signals are actually inside each `.mat` file?**

We will record variable names, shapes, data types, and basic numeric statistics where possible.

In [6]:
# ============================================================
# FIND MAT FILES
# ============================================================

mat_files = list(DATA_ROOT.rglob("*.mat")) if DATA_ROOT.exists() else []

print("MAT files found:", len(mat_files))
for p in mat_files:
    print(" -", p.relative_to(DATA_ROOT))

MAT files found: 12
 - Thermal Overstress Aging with DC at gate\20080429T135531.mat
 - Thermal Overstress Aging with Square Signal at gate\april22nd-23rdIgbtIRCG40BC30kd-A17.mat
 - Thermal Overstress Aging with Square Signal at gate and SMU data\Aging Data\Device 2\Device2  1.mat
 - Thermal Overstress Aging with Square Signal at gate and SMU data\Aging Data\Device 2\Device2b  1.mat
 - Thermal Overstress Aging with Square Signal at gate and SMU data\Aging Data\Device 2\Device2check  1.mat
 - Thermal Overstress Aging with Square Signal at gate and SMU data\Aging Data\Device 3\Device3  1.mat
 - Thermal Overstress Aging with Square Signal at gate and SMU data\Aging Data\Device 3\Device3b  1.mat
 - Thermal Overstress Aging with Square Signal at gate and SMU data\Aging Data\Device 3\Device3check  1.mat
 - Thermal Overstress Aging with Square Signal at gate and SMU data\Aging Data\Device 4\Device4  1.mat
 - Thermal Overstress Aging with Square Signal at gate and SMU data\Aging Data\Device 4\Device4b  1.mat
 - Thermal Overstress Aging with Square Signal at gate and SMU data\Aging Data\Device 5\Device5  1.mat
 - Thermal Overstress Aging with Square Signal at gate and SMU data\Aging Data\Device 5\Device5check  1.mat

In [7]:
# ============================================================
# INSPECT MATLAB VARIABLES
# ============================================================

def describe_array(name, value):
    result = {
        "variable": name,
        "python_type": type(value).__name__,
        "shape": str(getattr(value, "shape", None)),
        "dtype": str(getattr(value, "dtype", None)),
        "numeric": False,
        "n_elements": None,
        "min": None,
        "max": None,
        "mean": None,
        "std": None,
    }

    try:
        arr = np.asarray(value)
        result["n_elements"] = arr.size

        if np.issubdtype(arr.dtype, np.number):
            finite = arr[np.isfinite(arr)]
            result["numeric"] = True

            if finite.size:
                result["min"] = float(np.min(finite))
                result["max"] = float(np.max(finite))
                result["mean"] = float(np.mean(finite))
                result["std"] = float(np.std(finite))
    except Exception:
        pass

    return result


try:
    from scipy.io import loadmat
except ImportError:
    loadmat = None
    print("scipy is missing. Install it with: pip install scipy")


mat_inventory = []

if loadmat is not None:
    for path in mat_files:
        print("\n" + "=" * 80)
        print(path.relative_to(DATA_ROOT))
        print("=" * 80)

        try:
            data = loadmat(path, squeeze_me=False, struct_as_record=False)
            public_keys = [k for k in data.keys() if not k.startswith("__")]

            print("Variables:", public_keys)

            for key in public_keys:
                info = describe_array(key, data[key])
                info["file"] = str(path.relative_to(DATA_ROOT))
                mat_inventory.append(info)

                print(
                    f"{key:40s} "
                    f"shape={info['shape']:20s} "
                    f"dtype={info['dtype']}"
                )

        except Exception as e:
            print("Could not read with scipy.io.loadmat:", repr(e))
            print("If this is MATLAB v7.3, we will inspect it with HDF5/h5py next.")


mat_inventory_df = pd.DataFrame(mat_inventory)

if not mat_inventory_df.empty:
    display(mat_inventory_df)
    mat_inventory_df.to_csv("mat_variable_inventory.csv", index=False)
    print("Saved: mat_variable_inventory.csv")

================================================================================
Thermal Overstress Aging with DC at gate\20080429T135531.mat
================================================================================
Variables: ['index', 'x', 'gate_current', 'time', 'collector_current', 'heat_sink', 'package_temperture', 'gate_voltage', 'collector_voltage', 'GATE_VOLTAGE', 'COLLECTOR_VOLTAGE', 'HEAT_SINK_TEMP', 'GATE_CURRENT', 'COLLECTOR_CURRENT', 'TIME', 'PACKAGE_TEMP', 'current_time', 'current_date', 'data_path', 'comment']
index                                    shape=(1, 1)               dtype=int32
x                                        shape=(1,)                 dtype=<U18
gate_current                             shape=(1, 1)               dtype=float64
time                                     shape=(1, 1)               dtype=float64
collector_current                        shape=(1, 1)               dtype=float64
heat_sink                                shape=(1, 1)               dtype=float64
package_temperture                       shape=(1, 1)               dtype=float64
gate_voltage                             shape=(1, 1)               dtype=float64
collector_voltage                        shape=(1, 1)               dtype=float64
GATE_VOLTAGE                             shape=(1, 301680)          dtype=float64
COLLECTOR_VOLTAGE                        shape=(1, 301680)          dtype=float64
HEAT_SINK_TEMP                           shape=(1, 301680)          dtype=float64
GATE_CURRENT                             shape=(1, 301680)          dtype=float64
COLLECTOR_CURRENT                        shape=(1, 301680)          dtype=float64
TIME                                     shape=(1, 301680)          dtype=float64
PACKAGE_TEMP                             shape=(1, 301680)          dtype=float64
current_time                             shape=(1,)                 dtype=<U10
current_date                             shape=(1,)                 dtype=<U9
data_path                                shape=(1,)                 dtype=<U90
comment                                  shape=(0,)                 dtype=<U1

================================================================================
Thermal Overstress Aging with Square Signal at gate\april22nd-23rdIgbtIRCG40BC30kd-A17.mat
================================================================================
Variables: ['measurement']
measurement                              shape=(1, 1)               dtype=object

================================================================================
Thermal Overstress Aging with Square Signal at gate and SMU data\Aging Data\Device 2\Device2  1.mat
================================================================================
Variables: ['measurement']
measurement                              shape=(1, 1)               dtype=object

================================================================================
Thermal Overstress Aging with Square Signal at gate and SMU data\Aging Data\Device 2\Device2b  1.mat
================================================================================
Variables: ['measurement']
measurement                              shape=(1, 1)               dtype=object

================================================================================
Thermal Overstress Aging with Square Signal at gate and SMU data\Aging Data\Device 2\Device2check  1.mat
================================================================================
Variables: ['measurement']
measurement                              shape=(1, 1)               dtype=object

================================================================================
Thermal Overstress Aging with Square Signal at gate and SMU data\Aging Data\Device 3\Device3  1.mat
================================================================================
Variables: ['measurement']
measurement                              shape=(1, 1)               dtype=object

================================================================================
Thermal Overstress Aging with Square Signal at gate and SMU data\Aging Data\Device 3\Device3b  1.mat
================================================================================
Variables: ['measurement']
measurement                              shape=(1, 1)               dtype=object

================================================================================
Thermal Overstress Aging with Square Signal at gate and SMU data\Aging Data\Device 3\Device3check  1.mat
================================================================================
Variables: ['measurement']
measurement                              shape=(1, 1)               dtype=object

================================================================================
Thermal Overstress Aging with Square Signal at gate and SMU data\Aging Data\Device 4\Device4  1.mat
================================================================================
Variables: ['measurement']
measurement                              shape=(1, 1)               dtype=object

================================================================================
Thermal Overstress Aging with Square Signal at gate and SMU data\Aging Data\Device 4\Device4b  1.mat
================================================================================
Variables: ['measurement']
measurement                              shape=(1, 1)               dtype=object

================================================================================
Thermal Overstress Aging with Square Signal at gate and SMU data\Aging Data\Device 5\Device5  1.mat
================================================================================
Variables: ['measurement']
measurement                              shape=(1, 1)               dtype=object

================================================================================
Thermal Overstress Aging with Square Signal at gate and SMU data\Aging Data\Device 5\Device5check  1.mat
================================================================================
Variables: ['measurement']
measurement                              shape=(1, 1)               dtype=object

,variable,python_type,shape,dtype,numeric,n_elements,min,max,mean,std,file
0,index,ndarray,"(1, 1)",int32,True,1,3.016810e+05,3.016810e+05,3.016810e+05,0.000000,Thermal Overstress Aging with DC at gate\20080...
1,x,ndarray,"(1,)",<U18,False,1,NaN,NaN,NaN,NaN,Thermal Overstress Aging with DC at gate\20080...
2,gate_current,ndarray,"(1, 1)",float64,True,1,3.099858e-04,3.099858e-04,3.099858e-04,0.000000,Thermal Overstress Aging with DC at gate\20080...
3,time,ndarray,"(1, 1)",float64,True,1,3.292347e+09,3.292347e+09,3.292347e+09,0.000000,Thermal Overstress Aging with DC at gate\20080...
4,collector_current,ndarray,"(1, 1)",float64,True,1,7.894338e+00,7.894338e+00,7.894338e+00,0.000000,Thermal Overstress Aging with DC at gate\20080...
5,heat_sink,ndarray,"(1, 1)",float64,True,1,1.714580e-01,1.714580e-01,1.714580e-01,0.000000,Thermal Overstress Aging with DC at gate\20080...
6,package_temperture,ndarray,"(1, 1)",float64,True,1,3.051656e+02,3.051656e+02,3.051656e+02,0.000000,Thermal Overstress Aging with DC at gate\20080...
7,gate_voltage,ndarray,"(1, 1)",float64,True,1,-1.644894e-02,-1.644894e-02,-1.644894e-02,0.000000,Thermal Overstress Aging with DC at gate\20080...
8,collector_voltage,ndarray,"(1, 1)",float64,True,1,3.000472e+00,3.000472e+00,3.000472e+00,0.000000,Thermal Overstress Aging with DC at gate\20080...
9,GATE_VOLTAGE,ndarray,"(1, 301680)",float64,True,301680,-8.474687e-02,2.729620e+00,1.355372e+00,1.332899,Thermal Overstress Aging with DC at gate\20080...
10,COLLECTOR_VOLTAGE,ndarray,"(1, 301680)",float64,True,301680,1.583185e+00,9.988193e+00,5.728200e+00,3.980162,Thermal Overstress Aging with DC at gate\20080...
11,HEAT_SINK_TEMP,ndarray,"(1, 301680)",float64,True,301680,-9.791573e-01,1.046574e+00,2.140512e-01,0.352693,Thermal Overstress Aging with DC at gate\20080...
12,GATE_CURRENT,ndarray,"(1, 301680)",float64,True,301680,-2.235382e-04,1.126760e-02,5.149091e-03,0.004837,Thermal Overstress Aging with DC at gate\20080...
13,COLLECTOR_CURRENT,ndarray,"(1, 301680)",float64,True,301680,-6.192254e-02,9.791234e+00,4.162555e+00,3.768215,Thermal Overstress Aging with DC at gate\20080...
14,TIME,ndarray,"(1, 301680)",float64,True,301680,3.292332e+09,3.292347e+09,3.292340e+09,4354.375730,Thermal Overstress Aging with DC at gate\20080...
15,PACKAGE_TEMP,ndarray,"(1, 301680)",float64,True,301680,5.838286e+01,3.051656e+02,2.687947e+02,7.769160,Thermal Overstress Aging with DC at gate\20080...
16,current_time,ndarray,"(1,)",<U10,False,1,NaN,NaN,NaN,NaN,Thermal Overstress Aging with DC at gate\20080...
17,current_date,ndarray,"(1,)",<U9,False,1,NaN,NaN,NaN,NaN,Thermal Overstress Aging with DC at gate\20080...
18,data_path,ndarray,"(1,)",<U90,False,1,NaN,NaN,NaN,NaN,Thermal Overstress Aging with DC at gate\20080...
19,comment,ndarray,"(0,)",<U1,False,0,NaN,NaN,NaN,NaN,Thermal Overstress Aging with DC at gate\20080...
20,measurement,ndarray,"(1, 1)",object,False,1,NaN,NaN,NaN,NaN,Thermal Overstress Aging with Square Signal at...
21,measurement,ndarray,"(1, 1)",object,False,1,NaN,NaN,NaN,NaN,Thermal Overstress Aging with Square Signal at...
22,measurement,ndarray,"(1, 1)",object,False,1,NaN,NaN,NaN,NaN,Thermal Overstress Aging with Square Signal at...
23,measurement,ndarray,"(1, 1)",object,False,1,NaN,NaN,NaN,NaN,Thermal Overstress Aging with Square Signal at...
24,measurement,ndarray,"(1, 1)",object,False,1,NaN,NaN,NaN,NaN,Thermal Overstress Aging with Square Signal at...
25,measurement,ndarray,"(1, 1)",object,False,1,NaN,NaN,NaN,NaN,Thermal Overstress Aging with Square Signal at...
26,measurement,ndarray,"(1, 1)",object,False,1,NaN,NaN,NaN,NaN,Thermal Overstress Aging with Square Signal at...
27,measurement,ndarray,"(1, 1)",object,False,1,NaN,NaN,NaN,NaN,Thermal Overstress Aging with Square Signal at...
28,measurement,ndarray,"(1, 1)",object,False,1,NaN,NaN,NaN,NaN,Thermal Overstress Aging with Square Signal at...
29,measurement,ndarray,"(1, 1)",object,False,1,NaN,NaN,NaN,NaN,Thermal Overstress Aging with Square Signal at...
30,measurement,ndarray,"(1, 1)",object,False,1,NaN,NaN,NaN,NaN,Thermal Overstress Aging with Square Signal at...

Saved: mat_variable_inventory.csv

In [8]:
# ============================================================
# NUMERIC MATLAB VARIABLE SUMMARY
# ============================================================

if not mat_inventory_df.empty:
    numeric_vars = mat_inventory_df[
        mat_inventory_df["numeric"] == True
    ].copy()

    display(
        numeric_vars[
            ["file", "variable", "shape", "n_elements",
             "min", "max", "mean", "std"]
        ]
    )
else:
    print("No MATLAB variables were successfully inspected.")

,file,variable,shape,n_elements,min,max,mean,std
0,Thermal Overstress Aging with DC at gate\20080...,index,"(1, 1)",1,3.016810e+05,3.016810e+05,3.016810e+05,0.000000
2,Thermal Overstress Aging with DC at gate\20080...,gate_current,"(1, 1)",1,3.099858e-04,3.099858e-04,3.099858e-04,0.000000
3,Thermal Overstress Aging with DC at gate\20080...,time,"(1, 1)",1,3.292347e+09,3.292347e+09,3.292347e+09,0.000000
4,Thermal Overstress Aging with DC at gate\20080...,collector_current,"(1, 1)",1,7.894338e+00,7.894338e+00,7.894338e+00,0.000000
5,Thermal Overstress Aging with DC at gate\20080...,heat_sink,"(1, 1)",1,1.714580e-01,1.714580e-01,1.714580e-01,0.000000
6,Thermal Overstress Aging with DC at gate\20080...,package_temperture,"(1, 1)",1,3.051656e+02,3.051656e+02,3.051656e+02,0.000000
7,Thermal Overstress Aging with DC at gate\20080...,gate_voltage,"(1, 1)",1,-1.644894e-02,-1.644894e-02,-1.644894e-02,0.000000
8,Thermal Overstress Aging with DC at gate\20080...,collector_voltage,"(1, 1)",1,3.000472e+00,3.000472e+00,3.000472e+00,0.000000
9,Thermal Overstress Aging with DC at gate\20080...,GATE_VOLTAGE,"(1, 301680)",301680,-8.474687e-02,2.729620e+00,1.355372e+00,1.332899
10,Thermal Overstress Aging with DC at gate\20080...,COLLECTOR_VOLTAGE,"(1, 301680)",301680,1.583185e+00,9.988193e+00,5.728200e+00,3.980162
11,Thermal Overstress Aging with DC at gate\20080...,HEAT_SINK_TEMP,"(1, 301680)",301680,-9.791573e-01,1.046574e+00,2.140512e-01,0.352693
12,Thermal Overstress Aging with DC at gate\20080...,GATE_CURRENT,"(1, 301680)",301680,-2.235382e-04,1.126760e-02,5.149091e-03,0.004837
13,Thermal Overstress Aging with DC at gate\20080...,COLLECTOR_CURRENT,"(1, 301680)",301680,-6.192254e-02,9.791234e+00,4.162555e+00,3.768215
14,Thermal Overstress Aging with DC at gate\20080...,TIME,"(1, 301680)",301680,3.292332e+09,3.292347e+09,3.292340e+09,4354.375730
15,Thermal Overstress Aging with DC at gate\20080...,PACKAGE_TEMP,"(1, 301680)",301680,5.838286e+01,3.051656e+02,2.687947e+02,7.769160

## Excel inspection

Excel files may contain device IDs, aging logs, operating conditions, timestamps, or parameter characterization data.

In [9]:
# ============================================================
# EXCEL WORKBOOK INSPECTION
# ============================================================

excel_files = []

for ext in ("*.xlsx", "*.xls", "*.xlsm"):
    excel_files.extend(DATA_ROOT.rglob(ext))

print("Excel files found:", len(excel_files))

for p in excel_files:
    print(" -", p.relative_to(DATA_ROOT))


excel_inventory = []

for path in excel_files:
    try:
        xl = pd.ExcelFile(path)

        print("\n" + "=" * 80)
        print(path.relative_to(DATA_ROOT))
        print("Sheets:", xl.sheet_names)

        for sheet in xl.sheet_names:
            try:
                df = pd.read_excel(path, sheet_name=sheet)

                excel_inventory.append({
                    "file": str(path.relative_to(DATA_ROOT)),
                    "sheet": sheet,
                    "rows": len(df),
                    "columns": len(df.columns),
                    "columns_list": " | ".join(map(str, df.columns))
                })

                print(f"\nSheet: {sheet}")
                print("Shape:", df.shape)
                print("Columns:", list(df.columns))
                display(df.head(5))

            except Exception as e:
                print(f"Could not read sheet {sheet}: {e}")

    except Exception as e:
        print("Could not open:", path, "|", repr(e))


excel_inventory_df = pd.DataFrame(excel_inventory)

if not excel_inventory_df.empty:
    display(excel_inventory_df)
    excel_inventory_df.to_csv("excel_sheet_inventory.csv", index=False)
    print("Saved: excel_sheet_inventory.csv")

Excel files found: 1
 - Thermal Overstress Aging with Square Signal at gate and SMU data\Device Aging log.xls
Could not open: C:\Users\Abhishek Kuma\Desktop\BurnInWatch\dataset\Data\Thermal Overstress Aging with Square Signal at gate and SMU data\Device Aging log.xls | ImportError("Missing optional dependency 'xlrd'. Install xlrd >= 2.0.1 for xls Excel support Use pip or conda to install xlrd.")

In [10]:
# ============================================================
# SEARCH FOR LIKELY IMPORTANT FIELDS
# ============================================================

keywords = [
    "time", "timestamp", "date", "cycle", "sample",
    "voltage", "volt", "vce", "vge", "gate",
    "current", "amp", "collector", "ic",
    "temperature", "temp", "thermal",
    "power", "resistance", "rds", "rce",
    "device", "igbt", "mosfet", "aging", "age", "failure"
]

def keyword_hits(text):
    text = str(text).lower()
    return [k for k in keywords if k in text]


if not excel_inventory_df.empty:
    all_columns = []

    for value in excel_inventory_df["columns_list"].dropna():
        all_columns.extend(str(value).split(" | "))

    all_columns = sorted(set(all_columns))

    hits = pd.DataFrame({
        "field": all_columns,
        "possible_keywords": [
            ", ".join(keyword_hits(c)) for c in all_columns
        ]
    })

    display(hits[hits["possible_keywords"] != ""])
else:
    print("No Excel column inventory available yet.")

No Excel column inventory available yet.

## What we deliberately do NOT do yet

- No fabricated data
- No synthetic anomalies
- No arbitrary labels
- No random row-wise train/test split
- No arbitrary frontend fields
- No model training yet

After this notebook, we will create the **canonical cleaned CSV** from the actual measurements. Then we will do feature engineering, leakage-safe splitting, and unsupervised anomaly detection.